// <auto-generated />
using System;
using Employee_Verification_System.Admin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Verification_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103162550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AdminID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminID = 1,
                            Department = "IT",
                            Email = "admin@company.com",
                            FirstName = "System",
                            LastName = "Administrator",
                            Role = "Super Admin"
                        });
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.FraudDetection", b =>
                {
                    b.Property<string>("DetectionID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuspicionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DetectionID");

                    b.ToTable("FraudDetections");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportData")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("ReportID");

                    b.HasIndex("AdminID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Verification", b =>
                {
                    b.Property<string>("VerificationID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AdminID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VerificationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VerificationID");

                    b.HasIndex("AdminID");

                    b.HasIndex("EmployeeEmail");

                    b.HasIndex("Status");

                    b.HasIndex("VerificationDate");

                    b.ToTable("Verifications");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Report", b =>
                {
                    b.HasOne("Employee_Verification_System.Admin.Models.Admin", "Admin")
                        .WithMany("Reports")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Verification", b =>
                {
                    b.HasOne("Employee_Verification_System.Admin.Models.Admin", "Admin")
                        .WithMany("Verifications")
                        .HasForeignKey("AdminID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Employee_Verification_System.Admin.Models.Admin", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
